# requires the METALNX_ETC_DIR environment to 
services:
  metalnx:
      image: "metalnx" # 
      container_name: metalnx
      build:
        context: ..
        dockerfile: Dockerfile
      volumes:
        - ${METALNX_ETC_DIR}:/etc/irods-ext
      ports:
        - "8080:8080" 
      networks:
        - 4-2_irodsnet

networks:
   4-2_irodsnet:
    external: true
     


  
