#!/bin/bash

TMP_DIR=/tmp/emc-tmp
PROJECT_NAME="emc-metalnx-webapp"
PROJECT_VERSION="$1"
PROJECT_RELEASE="$2"

rm -rf $TMP_DIR

mkdir -p $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/tmp/emc-tmp

cp $WORKSPACE/emc-metalnx/emc-metalnx-web/target/emc-metalnx-web.war $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/tmp/emc-tmp/
cp $WORKSPACE/packaging/scripts/config_metalnx.sh $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/opt/emc/
cp $WORKSPACE/packaging/scripts/usage_information.sh $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/opt/emc/
cp -r $WORKSPACE/packaging/deb/DEBIAN $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/

chmod -R 755 $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/DEBIAN
sed -i "s/{{VERSION-NUMBER}}/$PROJECT_VERSION/" $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/DEBIAN/control
sed -i "s/{{BUILD-NUMBER}}/$PROJECT_RELEASE/" $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE/DEBIAN/control

dpkg-deb --build $TMP_DIR/$PROJECT_NAME-$PROJECT_VERSION-$PROJECT_RELEASE
